config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => "homepages#index"
  resources :sessions, only: [:create, :destroy, :new]
  resources :users, except: [:index]
  resources :artists do
    resources :shows, :except => [:index, :show]
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :shows, dependent: :destroy

end

app/models/show.rb
class Show < ActiveRecord::Base
  validates :location, presence: :true
  validates :date, presence: :true
  belongs_to :artist

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates_uniqueness_of :email


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def authorize
    redirect_to login_path, alert: "Sign Up or Sign In for Access." if current_user.nil?
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @artists = Artist.all
  end

  def create
    @artist = Artist.new(params[:artist])
    if @artist.save
      flash[:notice] = "Artist created!"
      redirect_to artists_path
    else
      render('new')
    end
  end

  def new
    @artist = Artist.new
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(params[:artist])
      flash[:notice] = "Artist name updated!"
      redirect_to artists_path
    else
      render 'edit'
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    flash[:notice] = "This artist has been deleted."
    redirect_to artists_path
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController

  def index
    @homepage_class = true
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Logged in!"
    else
      flash.alert = "Email or password is invalid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out!"
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :authorize

  def create
    @artist = Artist.find(params[:artist_id])
    @show = Show.new(params[:show])
    @artist.shows << @show
    if @show.save
      flash[:notice] = "New show created!"
      redirect_to artist_path(@artist)
    else
      render 'new'
    end
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @show = Show.new
    render 'new'
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    @show = Show.find(params[:id])
    if @show.update(params[:show])
      flash[:notice] = "Show name updated!"
      redirect_to shows_path
    else
      render 'edit'
    end
  end

  def destroy
    @show = Show.find(params[:id])
    @show.destroy
    flash[:notice] = "This show has been deleted."
    redirect_to shows_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "That's a new user you just created!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User updated successfully, bro!"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "That user is now dead."
    redirect_to artists_path
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<% content_for(:title, "Edit Artist | Concert Collector") %>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= render('layouts/alerts') %>
      <%= render("layouts/errors", :object => @artist) %>

      <h3>Update <%= @artist.name %></h3>
      <br>
      <%= form_for(@artist) do |f| %>
        <div class="form-group">
          <%= f.label "Name: " %>
          <%= f.text_field :name %>
        </div>
        <%= f.submit(:class => "btn btn-primary") %>
      <% end %>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<% content_for(:title, "Artists Home | Concert Collector") %>

<div class="jumbotron">
  <div class="container-fluid">
    <h2>Currently Tracked Artists</h2>
  </div>
</div>

<div class="container">
  <div class="row">
  <%= render('layouts/alerts') %>
    <ul>
      <% @artists.each do |artist| %>
        <h4><%= link_to "#{artist.name}", artist_path(artist.id) %></h4>
        <% end %>
    </ul>
  </div>
</div>

app/views/artists/new.html.erb
<% content_for(:title, "New Artist | Concert Collector") %>

<div class="container">
  <%= render("layouts/errors", :object => @artist) %>

  <h3>New Artist Addition</h3>
  <br>
  <%= form_for(@artist) do |f| %>
    <div class="form-group">
      <%= f.label "Name: " %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit(:class => "btn btn-primary") %>
  <% end %>
</div>

app/views/artists/show.html.erb
<% content_for(:title, "#{@artist.name} | Concert Collector") %>

<div class="jumbotron">
  <div class="container">
    <h2><%= @artist.name %></h2>
  </div>
</div>

<div class="container">
<%= render('layouts/alerts') %>
  <h3>Current collection of shows for <em><%= @artist.name %></em> :</h3>
  <ul>
    <% @artist.shows.each do |show| %>
      <li><%= show.date %> | <%= show.location %></li>
    <% end %>
  </ul>


  <br>
  <p><%= link_to "Add New Show", new_artist_show_path(@artist), :class => "btn btn-primary" %></p><br>
  <p><%= link_to "Edit Artist", edit_artist_path(@artist), :class => "btn btn-warning" %></p>
  <p><%= link_to "Delete Artist", artist_path(@artist),
                           :data => {:confirm => "You sure?",
                                     :method => "delete"},
                           :class => "btn btn-danger" %></p>
</div>

app/views/homepages/index.html.erb
<% content_for(:title, "Concert Collector | Home") %>

<body class="homepage">
  <div class="intro-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="intro-message">
            <h1>Welcome to Your Concert Collection</h1>
          </div>
          <h3><a href="/artists">Enter</a></h3>
        </div>
      </div>
    </div>
  </div>
    <div class="footer navbar-fixed-bottom">
      <div class="container">
        <p class="text-muted">photo via Sam Klein/flickr</p>
      </div>
    </div>
</body>

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger" role="alert">
  <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li class="warnings"><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/artists">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="/shows">Shows</a></li> -->
        <% if current_user %>
         <li><a href="/artists/new">Add Artist</a></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Logged in as #{current_user.email}", user_path(current_user) %></li>
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="<%= @homepage_class ? 'homepage' : ''%>">
  <%= render('layouts/header') %>

  <%= yield %>
</body>
</html>

app/views/shows/index.html.erb
<% content_for(:title, "All Shows | Concert Collector") %>

    <div class="jumbotron">
      <h3>Show Index:</h3>
    </div>

app/views/shows/new.html.erb
<% content_for(:title, "Add Show | Concert Collector") %>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= render("layouts/errors", :object => @show) %>

      <h3>Add a Show for <em><%= @artist.name %></em></h3><br>

      <%= form_for [@artist, @show] do |f| %>
        <div class="form-group">
          <%= f.label "Date: " %>
          <%= f.date_field :date %>
        </div>
        <div class="form-group">
          <%= f.label "Location: " %>
          <%= f.text_field :location, placeholder: "City, State" %>
        </div>
        <%= f.submit(:class => "btn btn-primary") %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit(class: "btn btn-primary") %>
<% end %>

app/views/users/edit.html.erb
<% content_for(:title, "User Edit | Concert Collector") %>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h1>Edit User</h1>
      <%= render("layouts/errors", :object => @user) %>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, "New User | Concert Collector") %>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= render("layouts/errors", :object => @user) %>
      <h1 class="text-center">Create New User</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:title, "#{@user.name} | Concert Collector") %>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= render('layouts/alerts') %>
      <h1>Welcome, <%= @user.name %>!</h1><br>

      <p><%= link_to "Edit User", edit_user_path, class: 'btn btn-primary' %></p>
      <p><%= link_to "Delete User", user_path, data: {confirm: "You're about to delete a user. Are you sure?",
                                                      method: "delete"},
                                                      class: "btn btn-danger" %></p>
    </div>
  </div>
</div>